<?php
/**
 * TL_ROOT/system/modules/translation-fields/languages/fa/modules.php
 * 
 * Contao extension: translation-fields 1.2.0 stable
 * Persian translation file 
 * 
 * Copyright : Daniel Kiesel 2013 
 * License   : LGPL 
 * Author    : Daniel Kiesel (iCodr8) 
 * Translator: Hamid Abbaszadeh (respinar), http://contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['translations']['0'] = "ترجمه‌ها";
 
?>
