<?php
/**
 * TL_ROOT/system/modules/translation_fields/languages/fa/tl_settings.php 
 * 
 * Contao extension: translation_fields 1.2.0 stable 
 * Persian translation file 
 * 
 * Copyright : Daniel Kiesel 2013 
 * License   : LGPL 
 * Author    : Daniel Kiesel (iCodr8) 
 * Translator: Hamid Abbaszadeh (respinar), http://contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['chooseTranslationLanguages']['0'] = "انتخاب زبان‌های موجود";
$GLOBALS['TL_LANG']['tl_settings']['chooseTranslationLanguages']['1'] = "این جعبه را برا تعریف زبان‌های موجود برای فیلدهای ترجمه انتخاب کنید.";
$GLOBALS['TL_LANG']['tl_settings']['translationLanguages']['0'] = "زبان‌های موجود";
$GLOBALS['TL_LANG']['tl_settings']['translationLanguages']['1'] = "اینجا می‌توانید از زبان‌های موجود برای فیلدهای ترجمعه انتخاب نمایید.";
$GLOBALS['TL_LANG']['tl_settings']['translation_fields_legend'] = "فیلدهای قابل ترجمه";
 
?>
