<?php
/**
 * TL_ROOT/system/modules/translation_fields/languages/fa/tl_translation_fields.php 
 * 
 * Contao extension: translation_fields 1.2.0 stable 
 * Persian translation file 
 * 
 * Copyright : Daniel Kiesel 2013 
 * License   : LGPL 
 * Author    : Daniel Kiesel (iCodr8) 
 * Translator: Hamid Abbaszadeh (respinar), http://contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_translation_fields']['fid']['0'] = "شناسه فیلد";
$GLOBALS['TL_LANG']['tl_translation_fields']['fid']['1'] = "این شناسه فیلد پیوند به فیلد ترجمه را فراهم می‌آورد";
$GLOBALS['TL_LANG']['tl_translation_fields']['language']['0'] = "زبان";
$GLOBALS['TL_LANG']['tl_translation_fields']['language']['1'] = "این فیلد پیوند به زبان را فراهم می‌آورد";
$GLOBALS['TL_LANG']['tl_translation_fields']['content']['0'] = "محتوا";
$GLOBALS['TL_LANG']['tl_translation_fields']['content']['1'] = "این فیلد محتوای ترجمه را نمایش می‌دهد";
$GLOBALS['TL_LANG']['tl_translation_fields']['translation_legend'] = "ترجمه";
$GLOBALS['TL_LANG']['tl_translation_fields']['new']['0'] = "ایجاد ترجمه جدید";
$GLOBALS['TL_LANG']['tl_translation_fields']['new']['1'] = "ایجاد ترجمه جدید";
$GLOBALS['TL_LANG']['tl_translation_fields']['edit']['0'] = "ویرایش ترجمه";
$GLOBALS['TL_LANG']['tl_translation_fields']['edit']['1'] = "ویرایش ترجمه شناسه %s";
$GLOBALS['TL_LANG']['tl_translation_fields']['delete']['0'] = "حذف ترجمه";
$GLOBALS['TL_LANG']['tl_translation_fields']['delete']['1'] = "حذف ترجمه شناسه %s";
$GLOBALS['TL_LANG']['tl_translation_fields']['show']['0'] = "نمایش ترجمه";
$GLOBALS['TL_LANG']['tl_translation_fields']['show']['1'] = "نمایش ترجمه شناسه %s";
 
?>
